### ISSUE TITLE
https://leanpub.com/forging-python/read#leanpub-auto-debugging

### ISSUE THREAD

**Issue by venkatveeramanidaasan** [tebeka/forging-python#3]
> "Graybeard: Yup. Note that **there are deploys and there are deploys**. Most of them will be a non issue, but some of them will give you a headache."

**there are deploys and there are deploys**

intentional?

**Comment by venkatveeramanidaasan** [comment]
> Graybeard: Also make you you can do a rollback as well. If a release goes **back** you need to be able to quickly get back. Blue-Green and rolling releases help with this.

back to bad or down?

**Comment by tebeka** [comment]
> there are deploys and there are deploys
> 
> > intentional?
> > Yes. Maybe the wrong idiom/phrasing. I'm saying that not all releases are the same, some are easy, some are difficult.

**Comment by tebeka** [comment]
> back to bad or down?
> typo, fixed. Thanks.
